[package]
name = "anony"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.11.0"
proc-macro2 = "1.0.66"
quote = "1.0.33"
syn = { version = "2.0.30", features = ["full"] }

[dev-dependencies]
serde = { version = "1.0.189", features = ["derive"] }
serde_json = "1.0.107"

[features]
default = []
serde = []

[[example]]
name = "anonymous_struct"
required-features = ["serde"]
