[package]
name = "anony"
version = "0.4.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Anonymous struct"
repository = "https://github.com/Blindfolded18/anony.git"
readme = "README.md"

[lib]
proc-macro = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proc-macro2 = "1.0.66"
quote = "1.0.33"
syn = { version = "2.0.30", features = ["full"] }

[dev-dependencies]
serde = { version = "1.0.189", features = ["derive"] }
serde_json = "1.0.107"
noop-waker = "0.1.0"
tokio = { version = "1.35.1", features = ["full"] }
futures = "0.3.30"

[features]
default = []
serde = []

[[example]]
name = "anonymous_struct"
required-features = ["serde"]
